AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to deploy an EC2 instance, clone a private Git repo, and set up a MAAP app on Docker.

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair for SSH access.
    Type: String

  InstanceType:
    Description: EC2 instance type.
    Type: String
    Default: t3.medium
    AllowedValues: [t2.micro, t3.medium, t3.large, t3.xlarge]

  AMIId:
    Description: AMI ID for the instance.
    Type: AWS::EC2::Image::Id
    Default: ami-005fc0f236362e99f

  SubnetId:
    Description: Subnet ID to deploy the instance.
    Type: AWS::EC2::Subnet::Id

  SecurityGroupId:
    Description: Security Group ID to associate with the instance.
    Type: AWS::EC2::SecurityGroup::Id

  VolumeSize:
    Description: Root volume size in GiB.
    Type: Number
    Default: 100

  TagName:
    Description: Name tag for the EC2 instance.
    Type: String
    Default: MAAP-Meta

  IAMInstanceProfile:
    Description: IAM instance profile ARN.
    Type: String

  GitRepoURL:
    Description: HTTP URL for the Git repository.
    Type: String

  MongoDBClusterName:
    Type: String
    Description: The name of the MongoDB Cluster
    Default: "MongoDBCluster-Meta"

  MongoDBUserName:
    Type: String
    Description: MongoDB User Name

  MongoDBPassword:
    Type: String
    Description: MongoDB Password

  APIPUBLICKEY:
    Type: String
    Description: MongoDB Atlas API_PUBLIC_KEY

  APIPRIVATEKEY:
    Type: String
    Description: MongoDB Atlas API_PRIVATE_KEY

  GROUPID:
    Type: String
    Description: MongoDB Atlas GROUP_ID

  AWSRegion:
    Description: AWS Region for the EC2 instance.
    Type: String
    Default: us-east-1

  AvailabilityZone:
    Type: String
    Description: EC2 Availability Zone

  LoggerReplicas:
    Description: Logger Service Replicas.
    Type: Number
    Default: 3

  LoaderReplicas:
    Description: Loader Service Replicas.
    Type: Number
    Default: 3

  MainReplicas:
    Description: Main Service Replicas.
    Type: Number
    Default: 3

  UIReplicas:
    Description: UI Service Replicas.
    Type: Number
    Default: 3

  AIMemoryReplicas:
    Description: AI Memory Service Replicas.
    Type: Number
    Default: 3

  SemanticCacheReplicas:
    Description: SemanticCache Service Replicas.
    Type: Number
    Default: 3

  TavilyAPIKey:
    Description: Tavily Web Search API Key.
    Type: String

  LLMModelID:
    Description: AI Memory LLM Model ID.
    Type: String
    Default: us.meta.llama3-3-70b-instruct-v1:0

  EmbeddingModelID:
    Description: Semantic Cache Embedding Model ID.
    Type: String
    Default: amazon.titan-embed-text-v1

  ReflectionAgent:
    Description: Model ID for AWS Bedrock.
    Type: String
    Default: us.meta.llama3-3-70b-instruct-v1:0

  SolutionAgent:
    Description: Model ID for AWS Bedrock.
    Type: String
    Default: us.meta.llama3-2-11b-instruct-v1:0

  InquiryAgent:
    Description: Model ID for AWS Bedrock.
    Type: String
    Default: us.meta.llama3-1-8b-instruct-v1:0

  GuidanceAgent:
    Description: Model ID for AWS Bedrock.
    Type: String
    Default: us.meta.llama3-3-70b-instruct-v1:0

  VisualAgent:
    Description: Model ID for AWS Bedrock.
    Type: String
    Default: us.meta.llama3-2-90b-instruct-v1:0

  CodingAgent:
    Description: Model ID for AWS Bedrock.
    Type: String
    Default: us.meta.llama3-1-8b-instruct-v1:0

  AnalyticsAgent:
    Description: Model ID for AWS Bedrock.
    Type: String
    Default: us.meta.llama3-3-70b-instruct-v1:0

  ReasoningAgent:
    Description: Model ID for AWS Bedrock.
    Type: String
    Default: us.meta.llama3-2-3b-instruct-v1:0

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref AMIId
      SubnetId: !Ref SubnetId
      AvailabilityZone: !Ref AvailabilityZone
      SecurityGroupIds:
        - !Ref SecurityGroupId
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: !Ref VolumeSize
            VolumeType: gp2
            DeleteOnTermination: true
      Tags:
        - Key: Name
          Value: !Ref TagName
      IamInstanceProfile: !Ref IAMInstanceProfile
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -euo pipefail

          LOG_FILE="/home/ubuntu/deployment.log"
          exec > >(tee -a "$LOG_FILE") 2>&1

          echo "Starting instance initialization at $(date)..."

          update_system() {
              echo "Updating system packages..."
              if ! sudo apt update -y; then
                  echo "System update failed. Continuing..."
              fi
          }

          install_packages() {
              echo "Installing required packages..."
              if ! sudo apt install -y python3 python3-pip git docker.io docker-compose ksh python3-venv; then
                  echo "Package installation failed. Continuing..."
              fi
          }

          configure_docker() {
              echo "Configuring Docker..."
              if ! sudo usermod -aG docker ubuntu; then
                  echo "Failed to add user to Docker group. Continuing..."
              fi
          }

          clone_repository() {
              echo "Cloning Git repository..."
              if ! sudo -u ubuntu git clone "${GitRepoURL}" /home/ubuntu/MAAP-Files; then
                  { echo "Git clone failed.  Exiting."; exit 1; }
              fi
              cd /home/ubuntu/MAAP-Files || { echo "MAAP-Files directory not found. Exiting."; exit 1; }
          }

          setup_env_file() {
              echo "Setting up environment variables..."
              cat <<EOF > /home/ubuntu/MAAP-Files/.env
          AWS_REGION=${AWSRegion}
          API_PUBLIC_KEY=${APIPUBLICKEY}
          API_PRIVATE_KEY=${APIPRIVATEKEY}
          GROUP_ID=${GROUPID}
          TAVILY_API_KEY=${TavilyAPIKey}
          LLM_MODEL_ID=${LLMModelID}
          EMBEDDING_MODEL_ID=${EmbeddingModelID}
          REFLECTION_AGENT=${ReflectionAgent}
          SOLUTION_AGENT=${SolutionAgent}
          INQUIRY_AGENT=${InquiryAgent}
          GUIDANCE_AGENT=${GuidanceAgent}
          VISUAL_AGENT=${VisualAgent}
          CODING_AGENT=${CodingAgent}
          ANALYTICS_AGENT=${AnalyticsAgent}
          REASONING_AGENT=${ReasoningAgent}
          EOF
          }

          pull_docker_images() {
              echo "Pulling Docker images..."
              docker-compose pull || { echo "Docker Compose pull failed. Exiting."; exit 1; }
          }

          deploy_mongodb() {
              echo "Deploying MongoDB cluster..."
              chmod +x mongodb_cluster_manager.ksh || echo "Failed to set executable permission for mongodb_cluster_manager.ksh."
              if ! ./mongodb_cluster_manager.ksh deploy "${MongoDBClusterName}" "${MongoDBUserName}" "${MongoDBPassword}"; then
                  { echo  "MongoDB cluster deployment failed. Exiting."; exit 1; }
              fi
              echo "Deploying MongoDB Vector Index and inserting data..."
              chmod +x mongodb_create_vectorindex.ksh || echo "Failed to set executable permission for mongodb_create_vectorindex.ksh."
              if ! ./mongodb_create_vectorindex.ksh; then
                  { echo  "MongoDB Vector Index deployment failed. Exiting."; exit 1; }
              fi
          }

          deploy_services() {
              echo "Starting Docker services..."
              export LOGGER_REPLICAS=${LoggerReplicas}
              export LOADER_REPLICAS=${LoaderReplicas}
              export MAIN_REPLICAS=${MainReplicas}
              export UI_REPLICAS=${UIReplicas}
              export AI_MEMORY_REPLICAS=${AIMemoryReplicas}
              export SEMANTIC_CACHE_REPLICAS=${SemanticCacheReplicas}
              
              echo "Setting replicas:"
              echo "Logger: $LOGGER_REPLICAS"
              echo "Loader: $LOADER_REPLICAS"
              echo "Main: $MAIN_REPLICAS"
              echo "UI: $UI_REPLICAS"
              echo "AIMemory: $AI_MEMORY_REPLICAS"
              echo "SemanticCache: $SEMANTIC_CACHE_REPLICAS"
              
              if ! docker-compose up -d; then
                  { echo "Docker Compose failed to start services. Exiting."; exit 1; }
              fi
          }

          main() {
              update_system
              install_packages
              configure_docker
              clone_repository
              setup_env_file
              pull_docker_images &
              deploy_mongodb
              deploy_services
              echo "Instance initialization completed at $(date)."
          }

          main

Outputs:
  InstanceId:
    Description: Instance ID of the deployed EC2 instance.
    Value: !Ref EC2Instance

  PublicDNS:
    Description: Public DNS of the deployed EC2 instance.
    Value: !GetAtt EC2Instance.PublicDnsName

  EC2PublicIP:
    Description: Public IPv4 address of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
